### ISSUE TITLE
Regression from 0.9.2 to 1.0.0

### ISSUE THREAD

**Issue by liamHowatt** [mgaitan/sphinxcontrib-mermaid#167] opened 2024-12-12 15:59 UTC
See https://github.com/lvgl/lvgl/pull/7453

See the link for the details. A flowchart that worked before has issues now. The flowchart code still works in the latest Mermaid live editor.

**Comment by timkpaine** [comment] 2024-12-13 20:00
can't reproduce 

<img width="1239" alt="Screenshot 2024-12-13 at 14 58 48" src="https://github.com/user-attachments/assets/25f47854-015b-440e-b136-d90e00c69cbd" />

possible conflict with another extension, possible duplicate of https://github.com/mgaitan/sphinxcontrib-mermaid/issues/81

**Closed by timkpaine** 2024-12-13 20:00 UTC
